### ISSUE TITLE
Provided .htaccess causes HTTP 500

### ISSUE THREAD

**Issue by syphernl** [fedecarg/apify-library#2]
The provided .htaccess file causes a HTTP 500 error, with this logged:

```
Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```

Renaming the file stops this behaviour.

**Comment by apifytech** [comment]
Can you try again but without the forward slash before index.php, e.g.:

RewriteEngine on 
RewriteRule !.(js|ico|gif|jpg|png|css|html)$ index.php

Thanks

**Comment by syphernl** [comment]
This indeed solves the issue.
