### ISSUE TITLE
Fetch error when loading /users or /users/1 examples

### ISSUE THREAD

**Issue by christarczon** [fedecarg/apify-library#4]
I had to remove the $this->entity parameter in the setFetchMode method call to make it work for me. Running the latest WAMP with PHP 5.3.4

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: fetch mode doesn't allow any extra arguments' in C:\wamp\apify\library\Model.php:136
Stack trace:
#0 C:\wamp\apify\library\Model.php(136): PDOStatement->setFetchMode(1048581, 'User')
#1 C:\wamp\apify\library\Model.php(200): Model->execute('SELECT \* FROM `...', Array)
#2 C:\wamp\apify\app\controllers\UsersController.php(27): Model->findAll()
#3 C:\wamp\apify\library\Request.php(232): UsersController->indexAction(Object(Request))
#4 C:\wamp\apify\public\index.php(8): Request->dispatch()
#5 {main}

**Comment by apifytech** [comment]
Removed extra argument. Thanks.
