### ISSUE TITLE
The static Entity::$updated property

### ISSUE THREAD

**Issue by jaapverloop** [fedecarg/apify-library#6]
I wonder why the Entity class does have a static "updated" property.

The Entity::setProperty() method is public and doesn't track any changes.

For example, given the following:

``` php
$entity = $model->findBy(array('foo' => 'bar'));
$entity->setProperty('foo', 'baz');
$model->update($entity);
```

The changes aren't persisted, because the Entity::addUpdated() method isn't called. But as long the Entity::addUpdated() method is public too, someone could mess with the changes anytime. So I guess it's intended behaviour to let the developer be reponsible for dealing with changes.

I do have another concern!

For example, given the following:

``` php
$user1 = $model->find(1);
$user1->username = 'foo';
$user2 = $model->find(2);
$user2->username = 'bar';
$model->update($user1);
$model->update($user2);
```

The changes of $user1 are persisted, but the changes for $user2 are lost because Entity::resetUpdated() is called from within the Model::update() method.

Do I miss something, am I wrong or is it intended?

**Comment by apifytech** [comment]
> The Entity::setProperty() method is public and doesn't track any changes. 

That's a good point. It's a public method, but intended to be accessed only within the class. I guess the 2 options are: changing the visibility of the method or adding some documentation to the DocBlock.

> The changes of $user1 are persisted, but the changes for $user2 are lost.

Yes, this can be an issue. It only works as expected if you update one user at a time. For example: 

``` php
$user1 = $model->find(1);
$user1->username = 'foo';
$model->update($user1);

$user2 = $model->find(2);
$user2->username = 'bar';
$model->update($user2);
```

There must be a better way to do this. Any suggestions?

**Comment by jaapverloop** [comment]
The SplObjectStorage could be used to track changes for each entity.

Something like (only additions and changes):

``` php
public function __construct(array $vars = null)
{
    if (self::$updated === null) {
        self::$updated = new SplObjectStorage();
    }

    $this->resetUpdated();
}

public function addUpdated($property)
{
     $updated = $this->getUpdated();
     $updated[] = $property;
     self::$updated[$this] = $updated;
}

/**
 * @return array
 */
public function getUpdated()
{
    return self::$updated[$this];
}

/**
 * @return array
 */
public function resetUpdated()
{
   self::$updated[$this] = array();
}
```

**Comment by apifytech** [comment]
Great, thanks! Apparently, SplObjectStorage performs better than an array http://codepad.org/XNoxN2UA

**Comment by jaapverloop** [comment]
Cool, I didn't know if the performance would be better, but it's a nice side effect!
